# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Yourssu-Incubating' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yourssu-Incubating
pod 'Then'
  target 'Yourssu-IncubatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Yourssu-IncubatingUITests' do
    # Pods for testing
  end

end
